
name: Apigee OAS-First pipeline

on: push


# Needed to write files to the repository (JOB2)
permissions:
  contents: write


env:
  APIGEE_DEPLOYMENT_SUFFIX: "-demo"

  # Default Target Apigee Organization et environment 
  # and Target Server URL are in .env file

  # GCP Service Account Key used to deploy proxy
  GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}

  # GCP Service Account email to be used to access GCP services from proxy
  # (specified at deployment step)
  APIGEE_GOOGLE_TOKEN_EMAIL: ${{ secrets.APIGEE_GOOGLE_TOKEN_EMAIL }}
  COMMIT_MESSAGE: ${{ github.event.head_commit.message }}

jobs:

# JOB 0 ------------------------------------------------------------------------

  initial-publish-to-apihub:
    if: "contains(github.event.head_commit.message, '[api-hub]')"
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Checkout script repository
        uses: actions/checkout@v4
        with:
          repository: g-lalevee/APIhub-apiData-builder
          path: .
          token: ${{ secrets.CHECKOUT_PAT }}


  # Generate SA key file from secret variable
      - name: Generate SA key file
        run: 
          pwd
          ls
          echo $GCP_SERVICE_ACCOUNT >  apihub/sa.json


  # Install apigee-go-gen
      - name: Install apigee-go-gen
        shell: bash
        run: |
          # bash install-apigee-go-gen 
          # change it to apigee-go-gen when issue fixed !!!!
          curl -s https://apigee.github.io/apigee-go-gen/install | sh


  # Update files
      - name: Build API hub plugin payload
        run: |
          chmod +x ./build-apiData.sh
          ./build-apiData.sh

          cat output.txt


